# Site settings

title: Livres DIY
email: contato@livres.diy
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Livres DIY - your destination for creative DIY book projects
  and crafting inspiration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://livres.diy" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: livresdiy
github_username: LivresDIY

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# GitHub Pages specific settings
repository: LivresDIY/livresdiy.github.io

# Header pages - specify which pages appear in navigation
# header_pages:
#   - index.html

